# Configurations for NEAT


INPUT_NEURONS = 10
OUTPUT_NEURONS = 1
POPULATION = 50
STAGNATED_SPECIES_THRESHOLD = 20
STAGNATIONS_ALLOWED = 2
CROSSOVER_CHANCE = 0.75
WEAK_SPECIES_THRESHOLD = 5
ACTIVATION_THRESHOLD = 0.5
WEIGHT_MUTATION_RATE = 0.8
UNIFORM_WEIGHT_MUTATION_RATE = 0.9
ADD_GENE_MUTATION = 0.05
ADD_NODE_MUTATION = 0.03
ENABLE_GENE_MUTATION_RATE = 0.0 # 0.0 means no reenabling of genes possible
COMPATIBILITY_THRESHOLD = 3.0
EXCESS_COMPATIBILITY_CONSTANT = 1.0
DISJOINT_COMPATIBILITY_CONSTANT = 1.0
WEIGHT_COMPATIBILITY_CONSTANT = 0.4

